version: "3.9"

services:
  db:
    image: postgres:14.1
    container_name: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=chargecenterdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password


  django:
    build:
      context: .
      dockerfile: docker/production.Dockerfile
    container_name: django
    command: docker/production_web_entrypoint.sh
    environment:
      - DATABASE_URL=psql://user:password@db:5432/chargecenterdb
      - MOCK_CHARGE_SERVICE_TOKEN_URL=http://mock_charge_flask:8822/apis/token/
      - MOCK_CHARGE_SERVICE_CHARGE_URL=http://mock_charge_flask:8822/apis/charge/
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure


  mock_charge_flask:
    image: python:3.9.9-slim
    working_dir: /app
    volumes:
      - ./services:/app
    ports:
      - "8822:8822"
    command: >
      sh -c "
        pip install -r requirements.txt &&
        gunicorn --workers 3 --worker-class gevent --bind 0.0.0.0:8822 wsgi:app
      "