version: "3.9"

services:

  postgres:
    image: postgres:14.2
    container_name: postgresql-ChargeCenter
    ports:
      - 5434:5432
    environment:
      - POSTGRES_DB=chargecenterdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin4_container-ChargeCenter
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 'pg_pass'
    ports:
      - "5050:80"

  rabbitmq:
    image: "rabbitmq:alpine"
    container_name: rabbitmq-ChargeCenter
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  redis:
    image: redis:7
    container_name: redis-ChargeCenter
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
    postgres-data:
    redis-data:

