# Generated by Django 4.0.7 on 2024-07-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='username',
            field=models.CharField(default='ad', max_length=150, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
    ]
