# Generated by Django 4.0.7 on 2024-07-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_baseuser_username'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='baseuser',
            name='users_baseu_email_97cf3e_idx',
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AddIndex(
            model_name='baseuser',
            index=models.Index(fields=['username'], name='users_baseu_usernam_2b7f3c_idx'),
        ),
    ]
