# Generated by Django 4.0.7 on 2024-07-11 06:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_remove_baseuser_users_baseu_email_97cf3e_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('position', models.PositiveIntegerField(default=0, editable=False, verbose_name='position')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PND', 'pending'), ('DN', 'done'), ('WTH', 'withdrawn')], default='PND', max_length=16, verbose_name='status')),
                ('amount', models.PositiveBigIntegerField(verbose_name='amount')),
                ('is_charge', models.BooleanField(verbose_name='is charge')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='users.salesperson', verbose_name='salesperson')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['salesperson'], name='transaction_salespe_59fb98_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['amount'], name='transaction_amount_7195ec_idx'),
        ),
    ]
