# Generated by Django 4.0.7 on 2024-07-11 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='number')),
                ('transaction_obj', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='concrete_charge_obj', to='transactions.transaction', verbose_name='transaction_obj')),
            ],
            options={
                'verbose_name': 'Charge Transaction',
                'verbose_name_plural': 'Charge Transactions',
            },
        ),
        migrations.CreateModel(
            name='BalanceTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='is confirmed')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='confirmed_transactions', to=settings.AUTH_USER_MODEL, verbose_name='confirmed by')),
                ('transaction_obj', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='concrete_balance_obj', to='transactions.transaction', verbose_name='transaction_obj')),
            ],
            options={
                'verbose_name': 'Balance Transaction',
                'verbose_name_plural': 'Balance Transactions',
            },
        ),
    ]
